# Generated by Django 5.0.1 on 2026-01-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_banner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="banner",
        ),
        migrations.AddField(
            model_name="profile",
            name="banner_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
