# Generated by Django 4.2.7 on 2026-02-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_profile_banner_profile_banner_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="fdfs_badge",
            field=models.BooleanField(default=False),
        ),
    ]
