# Generated by Django 5.0.1 on 2026-01-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_watched"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="poster_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="favorite",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="watched",
            name="poster_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="watched",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
